### ISSUE TITLE
BDD tests using Cucumber

### ISSUE THREAD

**Issue by Kodobocz** [BME-MIT-IET/iet-hf-2024-favagok#1]

**Comment by amurlamur** [comment]
Set up cucumber evironment. a4d02225efb93a9005afafffc80455fc4fd35e81

**Comment by amurlamur** [comment]
Add extra tests. c7c3ddf948d84ac4c369335585aed86a7523c6bc

**Comment by Kodobocz** [comment]
Committing more tests
e1bd036869f689dda1d90b82d8b9e2508fee54e5
