### ISSUE TITLE
Build + CI

### ISSUE THREAD

**Issue by wry6181** [BME-MIT-IET/iet-hf-2024-favagok#2]
Install Build framework Maven + CI GitHub Actions

**Comment by wry6181** [comment]
Fixed with commit 13f7cbf2ba5c7f0be920a0c0b503af3fc42b1c5c

**Comment by Kodobocz** [comment]
Setup Continuous Integration
0ddc55a58f4fda85dd5400845a8dfc8629a3986c
f7a4f1711c0d76e29ab6fd208416730766d17237
f7a101eb3686dfe153d1b39530e42fb41899cec5

**Comment by wry6181** [comment]
c994053c8bac5b73913eac5c4815f17ad99edc43 maven base setup

**Comment by wry6181** [comment]
d0d965013196e10321616bd6b3d0ea548b68a94e maven setup

**Comment by wry6181** [comment]
63bd92a811f3407ebc2ecd0f31f8ff6bd1fca127 import old project to maven project

**Comment by wry6181** [comment]
845c020229a8310963d4c9698e9f8eee1349404b maven build done fix image load
