### ISSUE TITLE
UI Tests

### ISSUE THREAD

**Issue by paleros** [BME-MIT-IET/iet-hf-2024-favagok#3]

**Comment by paleros** [comment]
[src/main/java/program/main/settings.java
](https://github.com/BME-MIT-IET/iet-hf-2024-favagok/blob/3f2a5d45d0b211bcb7b2c4d9ce64efc8811bcd62/src/main/java/program/main/settings.java#L128)
There is an aesthetic problem here.
There is an unnecessary space in the text.

**Comment by Kodobocz** [comment]
The tests are working! Looks just fine
